name: simple_preloader
description: "The widget to wait for the return of asynchronous calls with preload."
version: 1.0.1
homepage: https://github.com/leonardopinho/simple_preloader

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  custom_events: ^0.0.4
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

 assets:
   - assets/anim_1.json
   - assets/anim_2.json
   - assets/anim_3.json
   - assets/anim_4.json
   - assets/anim_5.json